Alois xx/main (#101)
* Updated to TraceProcessing v2

* - Updated to TraceProcessing v2
- The current beta of TraceProcessing v2 version does not support self contained single exe files
- Split Reading part from extraction into extra dll named ETWAnalyzer.Reader to be able to target still .NET 4.8 to read extracted data
- Removed Analyzers which were not used anyway by anyone
- Nuget package was always supposed to read extracted data so this should not be a breaking change
- Renamed Nuget package ETWAnalyzer to ETWAnalyzer.Reader
- Added example ETWAnalyzer.Reader.Test to show how one can access extracted data programatically

* - -Console mode added .clip 0/1 to enable/disable clipping output to console width. Once a dump command with -clip was used there was no way to unset it.
- Fix: Properly clip multiline strings. Now each line is clipped separately. This did lead to missing help or column headers when clipping was enabled.

* - Include xml doc file in nuget package
- Fix coding styles and usings
- Ignore not needed style errors
- Reduce API surface in ETWAnalyzer.Reader

* - Fix remaining code style issues
   - Use Primary constructors now
- Suppress not meaningful violations
Now we are at 0 warnings and messages everywhere.

* Fix: -dump TCP -issue post
 - Print also the file name in output

* - Allow for -processfmt s also -timedigits 0-6 to format process duration not with the default precision of 7 digits.
   e.g. -dump CPU -newProcess 1 -processfmt s -timedigits 0
   will print now
            xperf.exe(10152)     +47 - 48 0 s  instead of
            xperf.exe(10152)     +47 - 48 00:00:00.3639572
   Default without -timedigts was 7 digit precision:
            xperf.exe(10152)     +47.286 - 47.650 00:00:00.3639572

* -Fix: -dump  Process -parent pid  does not return parent processes which have already exited.
Now we return all child processes regardless if they still exit. Additionally the parent pid is also matching.

* Remove automatically added line from csproj which is not needed

* -Dump Process fix unit tests and make -tree process duration formatting consistent.

* -Dump TCP
   - Added
       -MinMaxBytes xx yy
       -MinMaxSentPackets xx yy
       -MinmaxReceivedPackets xx yy
       -MinMaxPackets xx yy

Breaking Changes:
 - Remove from range arguments of the form xx-yy the - sign
   All MinMax values with a - sign a separator are changed to use a space instead of a - sign.
   This is done to make range parsing consistent accross all commands and data types.
  The xx-yy format does not work with negative (especially time) values.

   -MinMaxReadyAvgus xx-yy
   -MinMaxReadyMs xx-yy
   -MinMaxCpuMs xx-yy
   -MinMaxWaitMs xx-yy
   -MinMaxWorkingSetMiB xx-yy
   -MinMaxWorkingSetPrivateMiB xx-yy
   -MinMaxCommitMiB xx-yy
   -MinMaxSharedCommitMiB xx-yy
   -MinMax[Read/Write/Total][Size/Time] xx-yy
   -MinMaxTotalCount xx-yy
   -MinMaxRetransDelayMs xx-yy
   -MinMaxRetransBytes xx-yy
   -MinMaxRetransCount xx-yy
   -MinMaxSentBytes xx-yy
   -MinMaxReceivedBytes xx-yy
   -MinMaxCSwitchCount xx-yy

* -Dump TCP
 - Added connection statistics filter which is written when connection is closed or when the last TcpConnectionSummary event was logged for an existing connection. This is done normally during trace start/stop. We use always the last event if more than one connection summary event exists.

  -MinMaxStatPacketsOut
  -MinMaxStatPacketsIn
  -MinMaxStatPackets
  -MinMaxStatBytesIn
  -MinMaxStatBytesOut
  -MinMaxStatBytes

 -Breaking:
  -Renamed -MinMaxSentDelayS to -MinMaxSendDelayS for naming consistency.

* Update version to 4.0.0.1

* Fix: -dump Stats: Do not crash when invalid files are loaded. Ignore them instead.

* Fix: ColorConsole was omitting multi line data.

* Fix: Improve error message when no file query was present.

* - Added Core usage support to spot Process Affinity issues. In CPU total view besides the Priority also the #Cores column is by default printed.
  To show not only the number of used cores but also on which cores a process did consume data you can add -ShowCoreNumber
  e.g. -dump CPU -ShowCoreNumber
  To omit printing core data add -NoCoreUsage

* Fix: Handle all locations where frame.Symbol.FunctionName can throw a NotSupportedException for legacy? msedge.dll pdbs. Ensure that errors are logged only once per image name to not clutter the log file.

* -Fix: Handle NullRef in -Dump Stats for random not extracted files.

* ColorConsole simplify remainder handling code.

* Fix: .load in console mode does only load .json and json7z files. Unrelated files are no longer tried to load which could lead to exceptions during query.

* -Fix: -extract TCP would print add a connection twice if connection was opened but not closed. The second connection would be shown as connection with no connect/disconnect time.

* - -Extract TCP will now also extract connection reset (RST) events which are sent sometimes by socket clients which cause different error handling paths in network receive code. .NET Code e.g. will get a
      SocketException: An existing connection was forcibly closed by the remote host.
  This is different from the -Reset flag which is sent by our machine when a socket connection could not  established:
       SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
     or data cannot be set because some firewall has dropped the connection in the meantime.

- -Dump TCP
        - Added -MinMaxClientResetS xx yy
             - Filter for connections which were closed with a RST package by client.
        - Enhanced -Column which allows to add columns with +colName which will add a column to the default set of columns.
          You can also mix it with ! to remove specific columns and add them to the default column set.

* - Harmonize in -dump tcp column names:
    - LastSendTime -> LastSentTime
    - LastReceiveTime -> LastReceivedTime

* Update -Dump TCP Documentation to currently supported fields.

* Fix: Add more null checks to be able to read old tcp data where TCP connection statistics is not present.

* Update -Dump TCP Screenshot with current version. Use ZScaler ETW file as example instead of random data.

* Added #Cores of -dump CPU -csv x.csv to CSV output file.

* Fix remaining symbol load exceptions in various places.
   process.GetSymbolForAddress can throw a NotSupportedExcepitons for various pdbs which are probabliy
in a not supported sub format.  See  https://github.com/microsoft/eventtracing-processing-samples/issues/12

* - Extract will now also report the number of processor groups
- OSName was reported as Windows 10 even for Windows 11. Use now WINSAT data to get a better name if this data was captured. xperf will not capture it by default but only wpr.
- Dump Stats now support property wildcards. e.g. -Dump stats -Properties *CPU*;*Processor* will now work.

* - Fix Compiler errors of C# 14 for Reverse calls
  https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/breaking-changes/compiler%20breaking%20changes%20-%20dotnet%2010#spant-and-readonlyspant-overloads-are-applicable-in-more-scenarios-in-c-14-and-newer

* Upgrade C-Runtime to Visual Studio 2026 supplied one v145

* Committing pending changes before starting .NET upgrade.

* Update to .NET 10.
Ignore some Nuget warnings for older packages which are not updated but link against vulnerable System.Drawing.dll which is not exposed by 7z compressor library. It is therefore safe to ignore this one.
We are also bound to System.Configuration 5.0 by SquidBox package as well which we use to do in memory compression/decompression without temp files.

* - Fix: NullReferenceException when Ready metric is extracted but MachineDetailsExtractor did not set CPU instance. Now we initialize a default instance all the time.

* Fix: Cache symbol load errors and do not try again for a failed image to make it debuggable if due to this many exceptions are thrown.

* Extract CPU Vendor from WinSAT data as well if previously it could not be found.

* Revert "- Fix: NullReferenceException when Ready metric is extracted but MachineDetailsExtractor did not set CPU instance. Now we initialize a default instance all the time."

This reverts commit 2aebc67d291cc3dd439a103dce7410489d5bc641.

* - Fix: NullReferenceException when Ready metric is extracted but MachineDetailsExtractor did not set CPU instance. Now we initialize a default instance all the time.

* -Dump Stat
    - Added WinSatOSName to dump OS name used during OS Install
    - Fixed test regression which did lead to outdated OS name.
    - Sometimes the WinSat Name is more up to date (Windows 11) sometimes the OS Name deduced by other means.

* Update make script to .NET 10.0

* Update build action

* Stay on VS2022 Toolset (v143) until VS2026 is rolled out to Github Windows Images.

* - Remove .NET 4.8 as upload target for ETWAnalyzer
- Update Build Workflow with .NET 10 Binaries
- Fix executable folder which is now in net10.0-windows folder

* Sync folder with github actions for binary upload

* Update sample folder for upload.

---------

Co-authored-by: Alois-xx <akraus1@gmx.de>